name: Test Global Package Installation

on:
  push:
    branches: [main, 1.x]
  pull_request:
  workflow_dispatch:

jobs:
  test-global-installation:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Package Globally
        run: |
          pip3 install xrpld-netgen

      - name: Verify Installation
        run: |
          xrpld-netgen up:standalone