#!/bin/bash

rippledconfig=`/bin/cat /app/config/rippled.cfg 2>/dev/null | wc -l`
validatorstxt=`/bin/cat /app/config/validators.txt 2>/dev/null | wc -l`

mkdir -p /config

if [[ "$rippledconfig" -gt "0" && "$validatorstxt" -gt "0" ]]; then

    echo "Existing rippled config at host /config/, using them."
    mkdir -p /etc/opt/ripple

    /bin/cat /app/config/rippled.cfg > /etc/opt/ripple/rippled.cfg
    /bin/cat /app/config/validators.txt > /etc/opt/ripple/validators.txt

fi

exec /app/rippled --conf /app/config/rippled.cfg "$@"